Traceback (most recent call last):
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaen8\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = ()  # empty tuple
b = (1, 'a', 2, 'b')
c = (3, 'c', 4)

# An ordered sequence
print("b[2] =", b[2])
# Tuple is additive
print(('aa',) + ('bb',))
print(a + b + c)
# Tuple can be sliced
print(b[1:])
print(b[1:2])
# Tuple has length
print(len(b + c))
# Tuple is immutable
b[0] = 0
------------------

----- stdout -----
b[2] = 2
('aa', 'bb')
(1, 'a', 2, 'b', 3, 'c', 4)
('a', 2, 'b')
('a',)
7
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[1], line 16[0m
[0;32m     14[0m [38;5;28mprint[39m([38;5;28mlen[39m(b [38;5;241m+[39m c))
[0;32m     15[0m [38;5;66;03m# Tuple is immutable[39;00m
[1;32m---> 16[0m [43mb[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m [38;5;241m=[39m [38;5;241m0[39m

[1;31mTypeError[0m: 'tuple' object does not support item assignment

