Traceback (most recent call last):
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaen8\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

img = np.load(".//data//arr3d.npy")

fig = plt.figure(1, figsize=(10,4), dpi=100)
ax1 = fig.add_subplot(141)
ax1.imshow(img)
ax1.axis("off")
ax2 = fig.add_subplot(142)
ax2.imshow(img[:,:,0], cmap="Reds")
ax2.axis("off")
ax3 = fig.add_subplot(143)
ax3.imshow(img[:,:,1], cmap='Greens')
ax3.axis("off")
ax4 = fig.add_subplot(144)
ax4.imshow(img[:,:,2], cmap='Blues')
ax4.axis("off")

plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[11], line 4[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m----> 4[0m img [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m.//data//arr3d.npy[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      6[0m fig [38;5;241m=[39m plt[38;5;241m.[39mfigure([38;5;241m1[39m, figsize[38;5;241m=[39m([38;5;241m10[39m,[38;5;241m4[39m), dpi[38;5;241m=[39m[38;5;241m100[39m)
[0;32m      7[0m ax1 [38;5;241m=[39m fig[38;5;241m.[39madd_subplot([38;5;241m141[39m)

File [1;32mO:\Envs\nycudopcs\Lib\site-packages\numpy\lib\npyio.py:427[0m, in [0;36mload[1;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[0;32m    425[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m    426[0m [38;5;28;01melse[39;00m:
[1;32m--> 427[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos_fspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[0;32m    428[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    430[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './/data//arr3d.npy'

